language: java
jdk:
  - oraclejdk7
  - openjdk7

after_script:
  - ant unittest

before_script:
  - psql -c 'create database unittest;' -U postgres
  - psql -c "create user tester with password 'tester';" -U postgres -d unittest

